FirmaEventos/urls.py
from django.conf.urls import url, include
from django.views.static import serve
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.views import (
    password_reset_confirm, password_reset_complete
    )

from users.forms import SetPasswordForm

urlpatterns = [
    url(r'^admin/', admin.site.urls),
  #  url(r'^captcha/', include('captcha.urls')),
    url(r'^sources/(?P<path>.*)$', serve,
        {'document_root': settings.MEDIA_ROOT}),
    url(r'^password/reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        password_reset_confirm,
        {'template_name': 'users_confirm_reset.html',
         'post_reset_redirect': '/password/done/',
         'set_password_form': SetPasswordForm},
        name='password_reset_confirm'),
    url(r'^password/done/$', password_reset_complete,
        {'template_name': 'users_pass_done.html'}),
    url(r'^', include('base.urls', namespace="base")),
    url(r'^', include('users.urls', namespace="users")),
    url(r'^', include('eventos.urls', namespace="events")),
    url(r'^', include('participantes.urls', namespace="participantes")),
]

base/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^$', StartView.as_view(), name='inicio'),
]

users/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from django.contrib.auth.views import (
    password_reset, password_reset_done,
    )

from .forms import PasswordResetForm
from .views import *


urlpatterns = [
    url(r'^login/$', LoginView.as_view(), name="login"),
    url(r'^logout/$', LogOutView.as_view(), name="logout"),

     # Reset password all users
    url(r'^password/reset/$', password_reset,
        {'post_reset_redirect': '/password/done/',
         'template_name': 'users_forgot.html',
         'password_reset_form': PasswordResetForm},
        name="forgot"),
    url(r'^password/done/$', password_reset_done,
        {'template_name': 'users_pass_reset_done.html'},
        name='reset_done'),
    
    url(r'^registro/$', UserFormView.as_view(),
        name='registro_ingreso_participante'),
    
    url(r'^actualizar-participante/$', UpdateUserFormView.as_view(),
        name='perfil_update_participante'),
    
    url(r'^consultar-participante/$', DetailUserForm.as_view(),
        name='perfil_consulta_participante'),

]

users/models.py
# -*- encoding: utf-8 -*-
"""!
Modelo que construye los modelos de datos de los usuarios

@author Ing. Leonel P. Hernandez M. (lhernandez at cenditel.gob.ve)
@copyright <a href='https://www.gnu.org/licenses/gpl-3.0.en.html'>GNU Public License versión 3 (GPLv3)</a>
@date 19-11-2017
@version 1.0.0
"""
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver



class Pais(models.Model):
    """!
    Clase que contiene los paises

    @author Ing. Yamil Orozco. (yjorozco at cnti.gob.ve)
    @copyright <a href='https://www.gnu.org/licenses/gpl-3.0.en.html'>GNU Public License versión 3 (GPLv3)</a>
    @date 25-10-2018
    @version 1.0.0
    """
    codigo = models.CharField(max_length=2)
    nombre = models.CharField(max_length=50)

    class Meta:
        """!
            Clase que construye los meta datos del modelo
        """
        verbose_name = 'Pais'
        verbose_name_plural = 'Pais'
        db_table = 'users_pais'

    def __str__(self):
        """!
        Fucncion que muestra el pais
        @return Devuelve el pais
        """
        return self.nombre

class Certificado(models.Model):
    """!
    Clase que contiene el id de los cerificados

    @author Ing. Yamil Orozco. (yjorozco at cnti.gob.ve)
    @copyright <a href='https://www.gnu.org/licenses/gpl-3.0.en.html'>GNU Public License versión 3 (GPLv3)</a>
    @date 25-10-2018
    @version 1.0.0
    """
    certificado = models.CharField(max_length=150)
    pais = models.ForeignKey(Pais, on_delete=models.CASCADE)
    pasaporte = models.CharField(max_length=50)  
    cargo = models.CharField(max_length=150)    
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    class Meta:
        """!
            Clase que construye los meta datos del modelo
        """
        verbose_name = 'Certificado'
        verbose_name_plural = 'Certificado'
        db_table = 'users_certificado'

    def __str__(self):
        """!
        Fucncion que muestra el evento

        @return Devuelve el identificador del evento
        """
        return self.pasaporte

users/views.py
# -*- encoding: utf-8 -*-
"""!
Vista que controla los procesos de los usuarios

@author Ing. Leonel P. Hernandez M. (leonelphm at gmail.com)
@copyright <a href='https://www.gnu.org/licenses/gpl-3.0.en.html'>GNU Public License versión 3 (GPLv3)</a>
@date 09-01-2017
@version 1.0.0
"""
from django.core import serializers
from django import forms
from django.db.models import Q
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import (
    authenticate, logout, login
)

from django.contrib.admin.models import LogEntry, ADDITION, CHANGE, DELETION
from django.contrib.auth.models import (
    Group, Permission, User
)
from django.contrib.auth.views import redirect_to_login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.contenttypes.models import ContentType
from django.contrib.messages.views import SuccessMessageMixin
from django.core.exceptions import PermissionDenied
from django.core.validators import validate_email
from django.core.urlresolvers import (
    reverse_lazy, reverse
)

from django.shortcuts import (
    render, redirect, get_object_or_404
)
from django.views.generic import TemplateView, UpdateView, View
from django.views.generic.base import RedirectView
from django.views.generic.edit import FormView
from multi_form_view import MultiModelFormView
from .forms import FormularioLogin
from .forms import UserForm
from .forms import CertificadoForm
from .forms import UpdateUserForm
from .forms import UpdateCertificadoForm
from base.views import LoginRequeridoPerAuth
from base.messages import MENSAJES_LOGIN, MENSAJES_START, MENSAJES_ARCHIVOS
from django.core.files.storage import FileSystemStorage
from django.http import HttpResponseRedirect
import requests
import os

from users.models import (
    Certificado
)


def handle_uploaded_file(file, name):
    with open('%s/%s' % (settings.TMP, name), 'wb+') as destination:
        for chunk in file.chunks():
            destination.write(chunk)

class LoginView(FormView):
    """!
    Muestra el formulario de ingreso a la aplicación 

    @author Ing. Leonel P. Hernandez M. (leonelphm at gmail.com)
    @copyright <a href='https://www.gnu.org/licenses/gpl-3.0.en.html'>GNU Public License versión 3 (GPLv3)</a>
    @date 09-01-2017
    @version 1.0.0
    """
    form_class = FormularioLogin
    template_name = 'users_login.html'
    success_url = reverse_lazy('base:inicio')

    def form_valid(self, form):
        """
        Valida el formulario de logeo
        @return: Dirige a la pantalla inicial de la plataforma
        """
        usuario = form.cleaned_data['usuario']
        contrasena = form.cleaned_data['contrasena']
        try:
            validate_email(usuario)
            try:
                usuario = User.objects.get(email=usuario).username
            except:
                messages.error(self.request, 'No existe este correo: %s \
                                              asociado a una cuenta' % (usuario))
        except Exception as e:
            print (e)


        usuario = authenticate(username=usuario, password=contrasena)

        if usuario is not None:
            login(self.request, usuario)

            if self.request.POST.get('remember_me') is not None:
                # Session expira a los dos meses si no se deslogea
                self.request.session.set_expiry(1209600)
            #messages.info(self.request, MENSAJES_START['INICIO_SESION'] % (usuario.first_name, usuario.username))
        else:
            self.success_url = reverse_lazy('users:login')
            user = User.objects.filter(username=form.cleaned_data['usuario'])
            if user:
                user = user.get()
                if not user.is_active:
                    messages.error(self.request, MENSAJES_LOGIN['CUENTA_INACTIVA'])
                else:
                    messages.warning(self.request, MENSAJES_LOGIN['LOGIN_USUARIO_NO_VALIDO'])

        return super(LoginView, self).form_valid(form)


class LogOutView(RedirectView):
    """!
    Salir de la apliacion

    @author Ing. Leonel P. Hernandez M. (leonelphm at gmail.com)
    @copyright <a href='https://www.gnu.org/licenses/gpl-3.0.en.html'>GNU Public License versión 3 (GPLv3)</a>
    @date 09-01-2017
    @version 1.0.0
    """
    permanent = False
    query_string = True

    def get_redirect_url(self):
        """!
        Dirige a la pantalla del login
        @return: A la url del login
        """
        logout(self.request)
        return reverse_lazy('users:login')

class UserFormView(FormView):
    
    form_class = UserForm
    template_name = "user_registration.html"
    second_form_class = CertificadoForm
    success_url = reverse_lazy('base:inicio')

    def get_context_data(self, **kwargs):
        context = super(UserFormView, self).get_context_data(**kwargs)
        if 'form' not in context:
            context['form'] = self.form_class()
        if 'form1' not in context:
            context['form1'] = self.second_form_class()
        return context


   # def get(self, request):
   #    form =  self.form_class(None)
   #    form1 = self.second_form_class(None)
   #    return render(request, self.template_name, {'form': form, 'form1': form1})

    
    def post(self, request, *args, **kwargs):

        form =  self.form_class(request.POST)
        form1 =  self.second_form_class(request.POST, request.FILES) 
        if form.is_valid() and form1.is_valid():
            consulta_api = None
            try:
                from botocore.vendored.requests.packages.urllib3.contrib import pyopenssl
                pyopenssl.extract_from_urllib3()
            except ImportError:
                pass        
            if len(request.FILES)>0:
                file =  request.FILES['certificado']
                handle_uploaded_file(request.FILES['certificado'], file)
                ruta = '%s/%s' % (settings.TMP, file)
                file = open(ruta, 'rb')
                files = {'upload': file}       
                print(file.name)   
                try:        
                    r = requests.post('https://localhost:8443/Murachi/0.1/archivos/p12cargar', verify=False, headers={'Authorization': 'Basic YWRtaW46YWRtaW4='}, files=files)
                    print(r.json())
                    consulta_api = r.json()['fileId']
                    # elimina el archivo si fue creado en la carpeta tmp
                    file.close()
                    os.unlink(ruta)
                except Exception as e:
                    print (e)
                    file.close()
                    os.unlink(ruta)
                    messages.error(self.request, MENSAJES_ARCHIVOS['ERROR_SUBIDA'] % ("el certificado"))
                    return self.render_to_response(self.get_context_data(form=form,form1=form1))
            user = form.save(commit=False)            
            username =  form.cleaned_data['username']
            password =  form.cleaned_data['password']
            email =  form.cleaned_data['email']
            first_name =  form.cleaned_data['first_name']
            last_name =  form.cleaned_data['last_name']
            user.first_name = first_name
            user.last_name = last_name
            user.username = username
            user.set_password(password)
            user.email = email
            user.save()
            certificado = form1.save(commit=False)                                    
            certificado.certificado = consulta_api
            pais = form1.cleaned_data['pais']
            certificado.pais = pais
            certificado.user = user
            certificado.save()
            return HttpResponseRedirect(self.get_success_url())
        else:            
            return self.render_to_response(self.get_context_data(form=form,form1=form1))



class UpdateUserFormView(FormView):
    """!
    Clase que permite actualizar los datos de un evento

    @author Ing. Leonel P. Hernandez M. (lhernandez at cenditel.gob.ve)
    @copyright <a href='https://www.gnu.org/licenses/gpl-3.0.en.html'>GNU Public License versión 3 (GPLv3)</a>
    @date 28-11-2017
    @version 1.0.0
    """
    model = Certificado
    form_class = UpdateUserForm
    template_name = 'user_update.html'
    success_url = reverse_lazy('users:perfil_consulta_participante')

    form_certificado = UpdateCertificadoForm

    def get_context_data(self, **kwargs):
        """!
        Metodo que permite cargar de nuevo valores en los datos de contexto de la vista

        @author Ing. Leonel P. Hernandez M. (lhernandez at cenditel.gob.ve)
        @copyright GNU/GPLv3
        @date 28-11-2017
        @param self <b>{object}</b> Objeto que instancia la clase
        @param kwargs <b>{object}</b> Objeto que contiene los datos de contexto
        @return Retorna los datos de contexto
        """
        context = super(UpdateUserFormView, self).get_context_data(**kwargs)
        user = User.objects.get(id=self.request.user.id)            
        certificado = Certificado.objects.get(user=user) 
        context['form'] =  self.form_class(instance=user)
        context['form1'] = self.form_certificado(instance=certificado)
        return context

    def post(self, request, *args, **kwargs):
        """!
        Metodo que permite actualizar y agregar mas participantes al evento

        @author Leonel P. Hernandez M (lhernandez at cenditel.gob.ve)
        @copyright GNU/GPLv3
        @date 29-11-2017
        @param request <b>{object}</b> Objeto que contiene la petición
        @return Retorna un mensaje de error o exito al success
        """

        userInstance = User.objects.get(id=self.request.user.id)           
        certificadoInstance = Certificado.objects.get(user=userInstance) 

        form =  self.form_class(request.POST, instance = userInstance)
        form1 =  self.form_certificado(request.POST, request.FILES, instance=certificadoInstance) 
        if form.is_valid() and form1.is_valid():

users/templates/user.detail.html
{% extends 'base.template.html' %}
{% load staticfiles %}
{% block title %}Ingresa{% endblock title %}
{% block content %}
    <div class="content center"> 

            <div class="row center">                
                <div class="col s12"><p class="flow-text">Actualización del Usuario</p></blockquote></div>
           </div>            
            <div class="row">              
                <div class="col s6 right-align"><i class="tiny material-icons prefix">account_circle</i>Usuario:</div>
                <div class="col s6 left-align">{{ usuario.username }}</div>                
            </div>                
            <div class="row">                               
                <div class="col s6 right-align"> <i class="tiny material-icons prefix">person</i>Nombre:</div>
                <div class="col s6 left-align">{{ usuario.first_name }}</div>                
            </div>
            <div class="row">              
               
                <div class="col s6  right-align"> <i class="tiny material-icons prefix">person</i>Apellido:</div>
                <div class="col s6  left-align">{{ usuario.last_name }}</div>
           
            </div>

            <div class="row">                
           
                <div class="col s6 right-align"><i class="tiny material-icons prefix">email</i>Email:</div>
                <div class="col s6 left-align">{{ usuario.email }}</div>
           
            </div>   
            
            <div class="row">             
           
                <div  class="col s6 right-align"><i class="tiny material-icons prefix">person</i>País:</div>
                <div  class="col s6 left-align">{{ certificado.pais }}</div>
           
            </div>
            
            <div class="row">             
           
                <div  class="col s6 right-align"><i class="tiny material-icons prefix">person</i>Cargo:</div>
                <div  class="col s6 left-align">{{ certificado.cargo }}</div>
           
            </div>

            <div  class="row">            
           
                <div class="col s6 right-align"><i class="tiny material-icons prefix">person</i>Pasaporte</div>
                <div class="col s6 left-align">{{ certificado.pasaporte }}</div>                                  
           
            </div>
                        
            <div class="row">
                        <a class="btn waves-effect colorazul" href="{% url 'users:perfil_update_participante' %}" >Actualizar</a>
            </div>
    </div>
{% endblock %}

users/templates/user_registration.html
{% extends 'base.template.html' %}
{% load staticfiles %}
{% block title %}Ingresa{% endblock title %}
{% block content %}
    <div class="content center">
        <form id="form" action="{% url 'users:registro_ingreso_participante' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="input-field {% if form.username.errors %}invalid{% endif %}">
                    <i class="tiny material-icons prefix">account_circle</i>
                    {{ form.username }}
                    <label for="icon_prefix {{ form.username.auto_id }}">Usuario</label>
                    {% include 'base.forms.errors.html' with form_errors=form.username.errors col_title_error='col s2' col_msg_error='col s10' %}
            </div>
                
            <div class="input-field {% if form.password.errors %}invalid{% endif %}">
                    <i class="tiny material-icons prefix">lock</i>
                    {{ form.password }}
                    <label for="icon_prefix {{ form.password.auto_id }}">Contraseña</label>
                    {% include 'base.forms.errors.html' with form_errors=form.password.errors col_title_error='col s2' col_msg_error='col s10' %}
            </div>   
                    
            <div class="input-field {% if form.first_name.errors %}invalid{% endif %}">
                <i class="tiny material-icons prefix">person</i>
                {{ form.first_name }}
                <label for="icon_prefix {{ form.first_name.auto_id }}">Nombre</label>
                {% include 'base.forms.errors.html' with form_errors=form.first_name.errors col_title_error='col s2' col_msg_error='col s10' %}
            </div>
            <div class="input-field {% if form.last_name.errors %}invalid{% endif %}">
                <i class="tiny material-icons prefix">person</i>
                {{ form.last_name }}
                <label for="icon_prefix {{ form.last_name.auto_id }}">Apellido</label>
                {% include 'base.forms.errors.html' with form_errors=form.last_name.errors col_title_error='col s2' col_msg_error='col s10' %}
            </div>

            <div class="input-field {% if form.email.errors %}invalid{% endif %}">
                    <i class="tiny material-icons prefix">email</i>
                    {{ form.email }}
                    <label for="icon_prefix {{ form.email.auto_id }}">Email</label>
                    {% include 'base.forms.errors.html' with form_errors=form.email.errors col_title_error='col s2' col_msg_error='col s10' %}
            </div>
            
            <div class="input-field {% if form1.cargo.errors %}invalid{% endif %}">
                    <i class="tiny material-icons prefix">person</i>
                    {{ form1.cargo }}
                    <label for="icon_prefix {{ form1.cargo.auto_id }}">Cargo</label>
                    {% include 'base.forms.errors.html' with form_errors=form1.cargo.errors col_title_error='col s2' col_msg_error='col s10' %}
            </div>

            <div class="input-field {% if form1.pasaporte.errors %}invalid{% endif %}">
                    <i class="tiny material-icons prefix">person</i>
                    {{ form1.pasaporte }}
                    <label for="icon_prefix {{ form1.pasaporte.auto_id }}">Pasaporte</label>
                    {% include 'base.forms.errors.html' with form_errors=form1.pasaporte.errors col_title_error='col s2' col_msg_error='col s10' %}
            </div>

            <div class="input-field col s12 {% if form1.pais.errors %}invalid{% endif %}" >
                <i class="tiny material-icons prefix">person</i>
                {{ form1.pais }}
                <label for="icon_prefix {{ form1.pais.auto_id }}">Pais</label>
                {% include 'base.forms.errors.html' with form_errors=form1.pais.errors col_title_error='col s2' col_msg_error='col s10' %}
            </div>
                        
            <div class="file-field input-field {% if form1.certificado.errors %}invalid{% endif %}">
                    <i class="tiny material-icons prefix">verified_user</i>
                    <div class="btn colorazul">
                        <span>Certificado</span>
                        <input type="file" name="certificado" accept=".p12">
                    </div>
                    <div class="file-path-wrapper">
                        <input class="file-path validate" type="text">
                    </div>
                    <label for="icon_prefix {{ form1.certificado.auto_id }}">Seleccionar Certificado</label>
                    {% include 'base.forms.errors.html' with form_errors=form1.certificado.errors col_title_error='col s2' col_msg_error='col s10' %}
            </div>
                    
            <button type="submit" class="btn waves-effect  colorazul">Entrar</button>
        </form>
    </div>
{% endblock %}

users/templates/user_update.html
{% extends 'base.template.html' %}
{% load staticfiles %}
{% block title %}Ingresa{% endblock title %}
{% block content %}
    <div class="content center">
        <form id="form" action="{% url 'users:perfil_update_participante' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="input-field {% if form.username.errors %}invalid{% endif %}">
                    <i class="tiny material-icons prefix">account_circle</i>
                    {{ form.username }}
                    <label for="icon_prefix {{ form.username.auto_id }}">Usuario</label>
                    {% include 'base.forms.errors.html' with form_errors=form.username.errors col_title_error='col s2' col_msg_error='col s10' %}
            </div>
                
            <!-- <div class="input-field {% if form.password.errors %}invalid{% endif %}">
                    <i class="tiny material-icons prefix">lock</i>
                    {{ form.password }}
                    <label for="icon_prefix {{ form.password.auto_id }}">Contraseña</label>
                    {% include 'base.forms.errors.html' with form_errors=form.password.errors col_title_error='col s2' col_msg_error='col s10' %}
            </div>    -->
                    
            <div class="input-field {% if form.first_name.errors %}invalid{% endif %}">
                <i class="tiny material-icons prefix">person</i>
                {{ form.first_name }}
                <label for="icon_prefix {{ form.first_name.auto_id }}">Nombre</label>
                {% include 'base.forms.errors.html' with form_errors=form.first_name.errors col_title_error='col s2' col_msg_error='col s10' %}
            </div>
            <div class="input-field {% if form.last_name.errors %}invalid{% endif %}">
                <i class="tiny material-icons prefix">person</i>
                {{ form.last_name }}
                <label for="icon_prefix {{ form.last_name.auto_id }}">Apellido</label>
                {% include 'base.forms.errors.html' with form_errors=form.last_name.errors col_title_error='col s2' col_msg_error='col s10' %}
            </div>

            <div class="input-field {% if form.email.errors %}invalid{% endif %}">
                    <i class="tiny material-icons prefix">email</i>
                    {{ form.email }}
                    <label for="icon_prefix {{ form.email.auto_id }}">Email</label>
                    {% include 'base.forms.errors.html' with form_errors=form.email.errors col_title_error='col s2' col_msg_error='col s10' %}
            </div>
            
            <div class="input-field {% if form1.cargo.errors %}invalid{% endif %}">
                    <i class="tiny material-icons prefix">person</i>
                    {{ form1.cargo }}
                    <label for="icon_prefix {{ form1.cargo.auto_id }}">Cargo</label>
                    {% include 'base.forms.errors.html' with form_errors=form1.cargo.errors col_title_error='col s2' col_msg_error='col s10' %}
            </div>

            <div class="input-field {% if form1.pasaporte.errors %}invalid{% endif %}">
                    <i class="tiny material-icons prefix">person</i>
                    {{ form1.pasaporte }}
                    <label for="icon_prefix {{ form1.pasaporte.auto_id }}">Pasaporte</label>
                    {% include 'base.forms.errors.html' with form_errors=form1.pasaporte.errors col_title_error='col s2' col_msg_error='col s10' %}
            </div>
            <div class="input-field col s12 {% if form1.pais.errors %}invalid{% endif %}" >
                    <i class="tiny material-icons prefix">person</i>
                    {{ form1.pais }}
                    <label for="icon_prefix {{ form1.pais.auto_id }}">Pais</label>
                    {% include 'base.forms.errors.html' with form_errors=form1.pais.errors col_title_error='col s2' col_msg_error='col s10' %}
            </div>
                        
            <div class="file-field input-field {% if form1.certificado.errors %}invalid{% endif %}">
                    <i class="tiny material-icons prefix">verified_user</i>
                    <div class="btn colorazul">
                        <span>Certificado</span>
                        <input type="file" name="certificado" accept=".p12">
                    </div>
                    <div class="file-path-wrapper">
                        <input class="file-path validate" type="text">
                    </div>
                    <label for="icon_prefix {{ form1.certificado.auto_id }}">Seleccionar Certificado</label>
                    {% include 'base.forms.errors.html' with form_errors=form1.certificado.errors col_title_error='col s2' col_msg_error='col s10' %}
            </div>
                  
            <button type="submit" class="btn waves-effect  colorazul">Entrar</button>
        </form>
    </div>
{% endblock %}

users/templates/users_confirm_reset.html
{% extends 'base.template.html' %}
{% load staticfiles %}
{% block title %}Recuperar contraseña{% endblock title %}
{% block content %}
<div class="center">
    <h3>Recuperar Contraseña</h3><hr/>
    {% if validlink %}
        <form id="forgot-password-form" method="post">
            {% csrf_token %}
            <br/>
            <p>Por favor ingrese su nueva contraseña dos veces.<br /> Así podremos verificar que es correcta.</p>
            
            <div class="input-field {% if form.new_password1.errors %}invalid{% endif %}">
                {{ form.new_password1 }}
                <label for="{{ form.new_password1.auto_id }}">Nueva Contraseña</label>
                {% include 'base.forms.errors.html' with form_errors=form.new_password1.errors col_title_error='col s2' col_msg_error='col s10' %}
            </div>
            
            <div class="input-field {% if form.new_password2.errors %}invalid{% endif %}">
                {{ form.new_password2 }}
                <label for="{{ form.new_password2.auto_id }}">Repita la Nueva Contraseña</label>
                {% include 'base.forms.errors.html' with form_errors=form.new_password2.errors col_title_error='col s2' col_msg_error='col s10' %}
            </div>
            <button type="submit" class="btn waves-effect colorazul">Cambiar</button>
        </form>
    {% else %}
        <div class="center">
            <h3>Se intento recuperar la contraseña, pero fallo.</h3><hr/>
            <p>El vínculo de recuperación de contraseña es inválido, <br />
            Posiblemente ya ha sido usado <br />
            Por favor solicite una nueva contraseña.</p>
    {% endif %}
</div>
{% endblock %}

users/templates/users_login.html
{% extends 'base.template.html' %}
{% load staticfiles %}
{% block title %}Ingresa{% endblock title %}
{% block content %}
    <div class="content center">
        <form id="form" action="{% url 'users:login' %}" method="post">
            {% csrf_token %}
            <div class="input-field {% if form.usuario.errors %}invalid{% endif %}">
                <i class="tiny material-icons prefix">account_circle</i>
                {{ form.usuario }}
                <label for="icon_prefix {{ form.usuario.auto_id }}">Usuario</label>
                {% include 'base.forms.errors.html' with form_errors=form.usuario.errors col_title_error='col s2' col_msg_error='col s10' %}
            </div>
            
            <div class="input-field {% if form.usuario.errors %}invalid{% endif %}">
                <i class="tiny material-icons prefix">lock</i>
                {{ form.contrasena }}
                <label for="icon_prefix {{ form.contrasena.auto_id }}">Contraseña</label>
                {% include 'base.forms.errors.html' with form_errors=form.usuario.errors col_title_error='col s2' col_msg_error='col s10' %}
            </div>
            <div class="row">
                    <a href="{% url 'users:registro_ingreso_participante' %}" style="cursor: pointer">¿Desea Registrarse?</a>
            </div>           
            <div class="row">
                <a href="{% url 'users:forgot' %}" style="cursor: pointer">¿Olvido su contraseña?</a>
            </div>
            
            <div class="row">
                <p class="center">
                    {{form.remember_me}}
                    <label for="id_remember_me">{{form.remember_me.label}}</label>
                </p>
            </div>
        <!--    <div class="row">
                <div class="col s4 offset-s5">
                    <div class="input-field {% if form.captcha.errors %}invalid{% endif %}">
                        <label>{{form.captcha.label}}</label>
                        <div class="col s7">
                            {{form.captcha}}
                        </div>
                        <a class="col s2" onclick="refresh_captcha(this);" style="cursor: pointer">
                            <i class="small material-icons">cached</i>
                        </a>
                        {% include 'base.forms.errors.html' with form_errors=form.captcha.errors col_title_error='col s2' col_msg_error='col s10' %}
                    </div>
                </div>
            </div>
            <div>-->
                <button type="submit" class="btn waves-effect colorazul">Entrar</button>
            </div>
            </div>
        </form>
    </div>
{% endblock %}

users/templates/users_pass_done.html
{% extends 'base.template.html' %}
{% load staticfiles %}
{% block title %}Recuperar Contraseña{% endblock title %}
{% block content %}
<div class="center">
    <h3>Recuperar Contraseña</h3><hr/>
        <br/>
        <p>Tu contraseña ha sido definida. Ya puedes iniciar sesión de nuevo.</p><br/>
        <a href="{% url 'users:login' %}" class="btn waves-effect colorazul">Iniciar sesión</a>
</div>
{% endblock %}