FirmaEventos/urls.py
from django.conf.urls import url, include
from django.views.static import serve
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.views import (
    password_reset_confirm, password_reset_complete
    )

from users.forms import SetPasswordForm

urlpatterns = [
    url(r'^admin/', admin.site.urls),
  #  url(r'^captcha/', include('captcha.urls')),
    url(r'^sources/(?P<path>.*)$', serve,
        {'document_root': settings.MEDIA_ROOT}),
    url(r'^password/reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        password_reset_confirm,
        {'template_name': 'users_confirm_reset.html',
         'post_reset_redirect': '/password/done/',
         'set_password_form': SetPasswordForm},
        name='password_reset_confirm'),
    url(r'^password/done/$', password_reset_complete,
        {'template_name': 'users_pass_done.html'}),
    url(r'^', include('base.urls', namespace="base")),
    url(r'^', include('users.urls', namespace="users")),
    url(r'^', include('eventos.urls', namespace="events")),
    url(r'^', include('participantes.urls', namespace="participantes")),
]

base/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^$', StartView.as_view(), name='inicio'),
]

participantes/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from .views import *

urlpatterns = [
    url(r'^search-participante/(?P<pk>\d+)/(?P<pasaporte>.+)$', ParticipanteEventoSearch.as_view(), name='search_participante'),
    url(r'^search-participante/$', ParticipanteEventoSearch.as_view(), name='search_participante_nid'),
    url(r'^update-participante-evento/$', AjaxParticipanteFirmaEvento.as_view(), name='update_participante_evento'),
    url(r'^participante-restante/(?P<evento>\d+)/$', ParticipantesRestantes.as_view(), name='participante_restante_evento'),
    url(r'^participante-restante/$', ParticipantesRestantes.as_view(), name='participante_restante_evento_nid'),
]

base/models.py
# -*- encoding: utf-8 -*-
"""!
Modelo que construye los modelos de datos de los usuarios

@author Ing. Leonel P. Hernandez M. (leonelphm at gmail.com)
@copyright <a href='https://www.gnu.org/licenses/gpl-3.0.en.html'>GNU Public License versión 3 (GPLv3)</a>
@date 09-06-2017
@version 1.0.0
"""
from django.db import models

base/views.py
# -*- coding: utf-8 -*-
"""!
Vista que construye los controladores para las utilidades de la plataforma

@author Ing. Leonel P. Hernandez M. (leonelphm at gmail.com)
@copyright <a href='https://www.gnu.org/licenses/gpl-3.0.en.html'>GNU Public License versión 3 (GPLv3)</a>
@date 09-06-2017
@version 1.0.0
"""
import json
from django.core.serializers.json import DjangoJSONEncoder
from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic import TemplateView
from django.contrib import messages
from django.contrib.auth.mixins import (
    PermissionRequiredMixin, LoginRequiredMixin
)
from django.shortcuts import (
    redirect
)

from .models import *
from .messages import MENSAJES_LOGIN


class LoginRequeridoPerAuth(LoginRequiredMixin):
    """!
    Clase que construye el controlador para el login requerido, se sobreescribe el metodo dispatch

    @author Ing. Leonel Paolo Hernandez Macchiarulo  (leonelphm at gmail.com)
    @copyright <a href='https://www.gnu.org/licenses/gpl-3.0.en.html'>GNU Public License versión 3 (GPLv3)</a>
    @date 09-06-2017
    @version 1.0.0
    """

    def dispatch(self, request, *args, **kwargs):
        """
        Envia una alerta al usuario que intenta acceder sin permisos para esta clase
        @return: Direcciona al login en caso de no poseer permisos, en caso contrario accede a la clase
        """
        if not request.user.is_authenticated:
            messages.warning(self.request, MENSAJES_LOGIN['LOGIN_REQUERIDO'])
            return self.handle_no_permission()
        valid_group = False
        grupos = request.user.groups.all()
        grupo = []
        if len(grupos) > 1:
            for g in grupos:
                grupo += str(g),
                if (str(g) in self.get_group_required()):
                    valid_group = True
        else:
            try:
                grupo = str(request.user.groups.get())
            except:
                return redirect('users:403error')
            if (grupo in self.get_group_required()):
                valid_group = True
        if not (valid_group):
            return redirect('users:403error')
        return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)


class StartView(TemplateView):
    """!
    Muestra el inicio de la plataforma

    @author Ing. Leonel Paolo Hernandez Macchiarulo  (leonelphm at gmail.com)
    @copyright <a href='https://www.gnu.org/licenses/gpl-3.0.en.html'>GNU Public License versión 3 (GPLv3)</a>
    @date 09-01-2017
    @version 1.0.0
    @return: El template inicial de la plataforma
    """
    template_name = "index.html"

base/templates/base.alert.messages.html
{% for message in messages %}
    {% if message %}
        <!-- Modal Structure -->
        <div id="modal_msg" class="modal">
          <div class="modal-content">
            <h4>Aviso</h4>
            <p>{{ message }}</p>
          </div>
          <div class="modal-footer">
            <a href="#!" class="modal-action modal-close waves-effect btn colorazul">Aceptar</a>
          </div>
        </div>
        <script type="text/javascript">

            $(document).ready(function(){
                $('#modal_msg').modal();
                $('#modal_msg').modal('open');
              
            });
       
        </script>
    {% endif %}
{% endfor %}

base/templates/base.footer.html
{% load staticfiles %}
<img src="{% static 'img/footer.png'%}">
<div class="colorazul">
    <div class="center" style="font-size: 12px; color:white">
        <p>
   
           <!--<span style="font: 12px Arial, sans-serif; display: inline-block; transform: rotate(180deg);">©</span>-->
            <span id="year-info-develop">{% now "Y" %}</span>
            CNTI. Portal desarrollado y administrado por el Centro Nacional de Tecnología de Información, adscrito al Ministerio del Poder Popular de Educación Universitaria, <br>
            Ciencia y Tecnología. Esta obra está bajo una licencia Creative Commons Reconocimiento - No Comercial - Compartir Igual 3.0 Venezuela. 

        </p>
    </div>
</div>

base/templates/base.forms.errors.html
{% if form_errors %}
    <div class="error-notice">
        <div class="error danger">
            <div class="row">
                <div class="{% if not col_title_error %}col s3{% else %}{{ col_title_error }}{% endif %}">
                    <!--<strong>Error</strong>-->
                </div>
                <div class="{% if not col_msg_error %}col s9{% else %}{{ col_msg_error }}{% endif %}">
                    {% if custom_message_error %}{{ custom_message_error }}{% else %}{{ form_errors }}{% endif %}
                </div>
            </div>

        </div>
    </div>
{% endif %}

base/templates/base.nav.bar.html
{% load staticfiles %}
<nav class="colorazul">
  <div class="nav-wrapper">
    <a class="brand-logo" href="{% url 'base:inicio' %}"><img src="{% static 'img/logo.png'%}"></a>
    {% if request.user.is_authenticated %}
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <li><a href="#!" class="dropdown-button" data-beloworigin="true" data-activates="dropdown1">Bienvenido <b>{{request.user.username}}</b> <i class="material-icons right">arrow_drop_down</i></a></li>
      <ul id='dropdown1' class='dropdown-content'>
        <li><a href="{% url 'users:perfil_consulta_participante' %}">Perfil</a></li>
        <li><a href="{% url 'users:logout' %}">Salir</a></li>
      </ul>
    </ul>
    {% else %}
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><a href="#">Bienvenido <b>Anónimo</b></a></li>
      </ul>
    {% endif %}
  </div>
</nav>
<img src="{% static 'img/head.png'%}">

base/templates/base.paginator.html
<ul class="pagination center  ">
    {% if paginator.has_previous %}
        <li>
            <span>
                <a href="?page={{ paginator.previous_page_number }}" class="waves-effect">
                    <i class="material-icons tiny" id="tiny">chevron_left</i> Anterior
                </a>
            </span>
        </li>
    {% endif %}
        <li>
            <span>Página {{ paginator.number }} de {{ paginator.paginator.num_pages }}.</span>
        </li>
    {% if paginator.has_next %}
        <li>
            <span>
                <a href="?page={{ paginator.next_page_number }}" class="waves-effect">
                    Siguiente <i class="material-icons" id="tiny">chevron_right</i>
                </a>
            </span>
        </li>
    {% endif %}
</ul>

base/templates/base.template.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset='UTF-8'>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no">
        <title>{% block title %}Murachi-LAT{% endblock %}</title>
        <link rel="stylesheet" type="text/css" href="{% static "materialize/css/materialize.min.css" %}"/>
        <link rel="stylesheet" type="text/css" href="{% static "materialize/material_icon/icon.css" %}"/>
        <link rel="stylesheet" type="text/css" href="{% static "css/style.css" %}"/>
        
        <script src="{% static "jquery/jquery-3.1.0.min.js" %}"></script>
        <script src="{% static "materialize/js/materialize.min.js" %}"></script>
        <script src="{% static "plugins/material-dialog/material-dialog.min.js" %}"></script>
        <script src="{% static "js/funciones.js" %}"></script>
        {% block headScript %}{%endblock%}
    </head>
    <body class="grey lighten-3">
        {% include 'base.nav.bar.html' %}
        <main>
        {% block superContent%}
            <div class="container">
                <div class="card-panel">
                    {% block content %}{% endblock %}
                </div>
            </div>
        {% endblock %}
        </main>
        {% block modals %}{% endblock %}
        {% include 'base.footer.html' %}
    </body>
    {% block extraJs %}{%endblock%}
    <script>
        $(document).ready(function() {
            $('select').material_select();
        });
    </script>
    {% include 'base.alert.messages.html' %}
    {% include 'base.vars.javascript.html' %}
</html>

base/templates/base.vars.javascript.html
{% load static from staticfiles %}
<script type="text/javascript">
    // URL para obtener data de usuario en evento
    var URL_USUARIO_EVENTO = "{% url 'participantes:search_participante_nid' %}";
    
    // URL para actualizar la firma de un participante
    var URL_ACTUALIZAR_PARTICIPACION = "{% url 'participantes:update_participante_evento' %}";
    
    // URL para comprobar si el firmante es el último
    var URL_ULTIMO_FIRMANTE = "{% url 'participantes:participante_restante_evento_nid' %}";
    
    // URL para comprobar si el documento esta siendo firmado
    var URL_COMPROBAR_FIRMA = "{% url 'events:comprobar_evento_nid' %}";

    // obtener el certificado firma digital
    var URL_BUSCAR_CERTIFICADO = "{% url 'events:buscar_certificado' %}";

            
</script>

base/templates/index.html
{% extends 'base.template.html' %}
{% block content %}
	<div class="center">
		<h3>Bienvenidos a Murachi-LAT</h3><hr/>
		{% if not request.user.is_authenticated %}
			<p>Si deseas ingresar al sistema haz click en <b>Ingresar</b></p>
			<a href="{% url 'users:login' %}" class="btn waves-effect btn colorazul">Ingresar</a>
		{% endif %}
		{% if request.user.is_authenticated %}
			<p>Para ver el historial de eventos, haz click en <b>Eventos</b></p>
			<a href="{% url 'events:list_events' %}" class="btn waves-effect btn colorazul">Eventos</a>
		{% endif %}
	</div>
{% endblock %}