FirmaEventos/urls.py
from django.conf.urls import url, include
from django.views.static import serve
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.views import (
    password_reset_confirm, password_reset_complete
    )

from users.forms import SetPasswordForm

urlpatterns = [
    url(r'^admin/', admin.site.urls),
  #  url(r'^captcha/', include('captcha.urls')),
    url(r'^sources/(?P<path>.*)$', serve,
        {'document_root': settings.MEDIA_ROOT}),
    url(r'^password/reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        password_reset_confirm,
        {'template_name': 'users_confirm_reset.html',
         'post_reset_redirect': '/password/done/',
         'set_password_form': SetPasswordForm},
        name='password_reset_confirm'),
    url(r'^password/done/$', password_reset_complete,
        {'template_name': 'users_pass_done.html'}),
    url(r'^', include('base.urls', namespace="base")),
    url(r'^', include('users.urls', namespace="users")),
    url(r'^', include('eventos.urls', namespace="events")),
    url(r'^', include('participantes.urls', namespace="participantes")),
]

base/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^$', StartView.as_view(), name='inicio'),
]

eventos/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from .views import *

urlpatterns = [
    # Url Access Super Admin
    # Crear y asignar participantes a eventos
    url(r'^crear-eventos/$', RegisterEvent.as_view(), name='create_events'),
    #Url Access all Users
    url(r'^lista-eventos/$', ListEvent.as_view(), name='list_events'),
    url(r'^firmar-evento/(?P<pk>\d+)$', SignEvent.as_view(),
        name='firma_events'),
    url(r'^detail-evento/(?P<pk>\d+)$', DetailEvent.as_view(),
        name='detail_event'),
    url(r'^comprobar-evento/(?P<event_id>\d+)$', EventoProcesado.as_view(),
        name='comprobar_evento'),
    url(r'^comprobar-evento/$', EventoProcesado.as_view(),
        name='comprobar_evento_nid'),
    url(r'^actualizar-evento/(?P<event_id>\d+)$', UpdateFileEvent.as_view(),
        name='update_evento'),
    url(r'^actualizar-evento-participantes/(?P<pk>[\w-]+)$', UpdateEventView.as_view(),
        name='update_evento_participante'),
    url(r'^buscar-certificado/$', BuscaCertificado.as_view(), name='buscar_certificado'),    
    url(r'^validar-firma/(?P<file_name>[\w\.-]+)$', ValidarFirma.as_view(), name='validar_firma'),
    
]

eventos/forms.py
from django import forms
from django.forms.fields import (
    CharField, BooleanField
)

from .models import *


class EventoForm(forms.ModelForm):
    """!
    Clase que permite crear el formulario para  el create or update del evento

    @author Ing. Leonel P. Hernandez M. (lhernandez at cenditel.gob.ve)
    @copyright <a href='https://www.gnu.org/licenses/gpl-3.0.en.html'>GNU Public License versión 3 (GPLv3)</a>
    @date 19-11-2017
    @version 1.0.0
    """
    archivo = CharField()

    class Meta:
        """!
            Clase que construye los meta datos del formulario
        """
        model = Evento
        exclude = ['activo', 'serial']

    def __init__(self, *args, **kwargs):
        """!
            Funcion que construye los valores iniciales del formulario evento
        """
        super(EventoForm, self).__init__(*args, **kwargs)
        self.fields['nombre_evento'].widget.attrs.update(
            {'class': 'form-control',
             'placeholder': 'Nombre del evento'})
        self.fields['fecha'].widget.attrs.update(
            {'class': 'datepicker',
             'placeholder': 'Fecha',
             'readonly':
             'readonly'})
        self.fields['archivo'].required = False
        self.fields['archivo'].widget.attrs.update(
            {'class': 'file-path validate',
             'placeholder': 'Subir Archivo',
             'accept': '.pdf'})
        self.fields['pos_x'].widget = forms.HiddenInput()
        self.fields['pos_x'].required=False
        self.fields['pos_y'].widget = forms.HiddenInput()
        self.fields['pos_y'].required=False
        self.fields['pag'].widget = forms.HiddenInput()
        self.fields['pag'].required=False


class FirmaEventoForm(forms.Form):
    """!
    Clase que permite crear el formulario para la firma de un documento

    @author Rodrigo Boet (rboet at cenditel.gob.ve)
    @copyright <a href='https://www.gnu.org/licenses/gpl-3.0.en.html'>GNU Public License versión 3 (GPLv3)</a>
    @date 20-11-2017
    @version 1.0.0
    """
    pasaporte = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Ingrese su pasaporte'}))


class UpdateFileEventoForm(forms.Form):
    """!
    Clase que permite crear el formulario para subir un documento a un evento

    @author Ing. Leonel P. Hernandez M. (lhernandez at cenditel.gob.ve)
    @copyright <a href='https://www.gnu.org/licenses/gpl-3.0.en.html'>GNU Public License versión 3 (GPLv3)</a>
    @date 19-11-2017
    @version 1.0.0
    """
    archivo = CharField()
    pos_x = CharField()
    pos_y = CharField()
    pag = CharField()

    class Meta:
        """!
            Clase que construye los meta datos del formulario
        """
        fields = ['archivo']

    def __init__(self, *args, **kwargs):
        """!
            Funcion que construye los valores iniciales del formulario evento
        """
        super(UpdateFileEventoForm, self).__init__(*args, **kwargs)
        self.fields['archivo'].required = True
        self.fields['archivo'].widget.attrs.update(
            {'class': 'file-path validate',
             'placeholder': 'Subir Archivo',
             'accept': '.pdf'})
        self.fields['pos_x'].required = True
        self.fields['pos_x'].widget = forms.HiddenInput()
        self.fields['pos_y'].required = True
        self.fields['pos_y'].widget = forms.HiddenInput()
        self.fields['pag'].required = True
        self.fields['pag'].widget = forms.HiddenInput()


class UpdateEventoForm(forms.ModelForm):
    """!
    Clase que permite crear el formulario para el update del evento

    @author Ing. Leonel P. Hernandez M. (lhernandez at cenditel.gob.ve)
    @copyright <a href='https://www.gnu.org/licenses/gpl-3.0.en.html'>GNU Public License versión 3 (GPLv3)</a>
    @date 28-11-2017
    @version 1.0.0
    """
    class Meta:
        """!
            Clase que construye los meta datos del formulario
        """
        model = Evento
        fields = ['nombre_evento', 'fecha']

    def __init__(self, *args, **kwargs):
        """!
            Funcion que construye los valores iniciales del formulario update evento
        """
        super(UpdateEventoForm, self).__init__(*args, **kwargs)
        self.fields['nombre_evento'].widget.attrs.update(
            {'class': 'form-control',
             'placeholder': 'Nombre del evento'})
        self.fields['fecha'].widget.attrs.update(
            {'class': 'datepicker',
             'placeholder': 'Fecha',
             'readonly':
             'readonly'})

eventos/views.py
# -*- encoding: utf-8 -*-

import os
import requests
import json
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.files.base import ContentFile
from django.core.files.storage import default_storage
from django.core.urlresolvers import reverse_lazy
from django.http import JsonResponse
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from requests.packages.urllib3.exceptions import InsecureRequestWarning
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
requests.packages.urllib3.disable_warnings(InsecureRequestWarning)
import requests
import logging
logging.basicConfig(level=logging.DEBUG)
from django.shortcuts import (
    redirect
)
from django.http import HttpResponse
from django.views import View
from django.views.generic import (
    ListView, FormView, UpdateView
)
from django.views.generic.edit import UpdateView
from django.views.generic.detail import DetailView

from multi_form_view import MultiModelFormView

from .forms import *
from participantes.forms import (
    FormsetParticipanteEvento
)
from .models import Evento
from participantes.models import (
    Participante, ParticipanteEvento
)
from users.models import (
    Certificado
)

import base64

def handle_uploaded_file(file, name):
    with open('%s/%s' % (settings.TMP, name), 'wb+') as destination:
        for chunk in file.chunks():
            destination.write(chunk)


class RegisterEvent(LoginRequiredMixin, FormView):
    """!
    Muestra el formulario de registro de usuarios

    @author Ing. Leonel P. Hernandez M. (lhernandez at cenditel.gob.ve)
    @copyright <a href='https://www.gnu.org/licenses/gpl-3.0.en.html'>GNU Public License versión 3 (GPLv3)</a>
    @date 20-11-2017
    @version 1.0.0
    """

    template_name = "register.event.html"
    form_class = EventoForm
    form_participante = FormsetParticipanteEvento
    success_url = reverse_lazy('base:inicio')

    def get_context_data(self, **kwargs):
        context = super(RegisterEvent, self).get_context_data(**kwargs)
        if 'form' not in context:
            context['form'] = self.form_class()
        if 'form2' not in context:
            context['form2'] = self.form_participante(queryset=Participante.objects.none())
        return context

    def post(self, request, *args, **kwargs):
        """!
        Metodo que permite registra y agregar participantes al evento

        @author Leonel P. Hernandez M (lhernandez at cenditel.gob.ve)
        @copyright GNU/GPLv3
        @date 20-11-2017
        @param request <b>{object}</b> Objeto que contiene la petición
        @return Retorna un mensaje de error o exito al success
        """
        nuevo_participante = self.form_participante(request.POST)
        consulta_api = None
        try:
            from botocore.vendored.requests.packages.urllib3.contrib import pyopenssl
            pyopenssl.extract_from_urllib3()
        except ImportError:
            pass        
        if len(request.FILES)>0:
            file =  request.FILES['file']
            handle_uploaded_file(request.FILES['file'], file)
            ruta = '%s/%s' % (settings.TMP, file)
            file = open(ruta, 'rb')
            files = {'file': file}
            print(files)
            try:
                r = requests.post('https://localhost:8443/Murachi/0.1/archivos/cargar', verify=False, headers={'Authorization': 'Basic YWRtaW46YWRtaW4='}, files=files)
                print(r.json())
                consulta_api = r.json()['fileId']
                # elimina el archivo si fue creado en la carpeta tmp
                file.close()
                os.unlink(ruta)
            except Exception as e:
                print (e)
                file.close()
                os.unlink(ruta)
                messages.error(self.request, "Error al conectar al servidor y subir\
                                              el archivo a la api Murachi")
                return redirect(self.success_url)
        try:

            if self.form_class(request.POST).is_valid() and nuevo_participante.is_valid():
                nuevo_evento = self.form_class(request.POST, request.FILES).save(commit=False)
                nuevo_evento.serial = consulta_api

                for form in nuevo_participante:
                    instance = form.save(commit=False)
                    if instance.nombres == '' or instance.apellidos == '' or instance.pasaporte == '':
                        messages.error(self.request, "Ninguno de los campos del\
                                                      participante puede estar\
                                                      vacio excepto el correo")
                        return redirect(self.success_url)
                nuevo_evento.save()
                # Control para guardar y asignar participantes al evento
                for form in nuevo_participante:
                    if form.cleaned_data.get('DELETE') and form.instance.pk:
                        form.instance.delete()
                    else:
                        instance = form.save(commit=False)
                        parametros = {
                                        'nombres': instance.nombres,
                                        'apellidos': instance.apellidos,
                                        'correo': instance.correo
                                        }
                        nuevo_participante, create = Participante.objects.update_or_create(pasaporte=instance.pasaporte, defaults=parametros)
                        asigna_evento = ParticipanteEvento(
                                        fk_participante=nuevo_participante,
                                        fk_evento=nuevo_evento)
                        asigna_evento.save()
                messages.success(self.request, "El usuario %s, ha creado con exito,\
                                            un nuevo evento %s" %
                                 (str(self.request.user),
                                  str(nuevo_evento)))
            else:
                messages.error(self.request, "Existe un error en el\
                                              Formualario %s %s" %
                               (self.form_class(request.POST).errors,
                                self.form_participante(request.POST).errors))
        except Exception as e:
            print (e)
            messages.error(self.request, "Esta intentando realizar una\
                                          acción incorrecta")

        return redirect(self.success_url)


class ListEvent(ListView):
    """!
    Muestra el listado de eventos

    @author Rodrigo Boet (rboet at cenditel.gob.ve)
    @copyright <a href='https://www.gnu.org/licenses/gpl-3.0.en.html'>GNU Public License versión 3 (GPLv3)</a>
    @date 20-11-2017
    @version 1.0.0
    """
    model = Evento
    template_name = "evento.list.html"
    paginate_by = 5


class SignEvent(FormView):
    """!
    Muestra el formulario para buscar y luego firmar documento

    @author Rodrigo Boet (rboet at cenditel.gob.ve)
    @copyright <a href='https://www.gnu.org/licenses/gpl-3.0.en.html'>GNU Public License versión 3 (GPLv3)</a>
    @date 20-11-2017
    @version 1.0.0
    """
    form_class = FirmaEventoForm
    template_name = "evento.firma.html"

    def get_context_data(self, **kwargs):
        """!
        Metodo que permite cargar de nuevo valores en los datos de contexto de la vista

        @author Rodrigo Boet (rboet at cenditel.gob.ve)
        @copyright GNU/GPLv3
        @date 20-11-2017
        @param self <b>{object}</b> Objeto que instancia la clase
        @param kwargs <b>{object}</b> Objeto que contiene los datos de contexto
        @return Retorna los datos de contexto
        """
        kwargs['nombre_evento'] = Evento.objects.get(pk=int(self.kwargs['pk']))
        return super(SignEvent, self).get_context_data(**kwargs)


class DetailEvent(DetailView):
    """!
    Muestra el detalle del evento

    @author Rodrigo Boet (rboet at cenditel.gob.ve)
    @copyright <a href='https://www.gnu.org/licenses/gpl-3.0.en.html'>GNU Public License versión 3 (GPLv3)</a>
    @date 20-11-2017
    @version 1.0.0
    """
    model = Evento
    template_name = "evento.detail.html"

    def get_context_data(self, **kwargs):
        """!
        Metodo que permite cargar de nuevo valores en los datos de contexto de la vista

        @author Rodrigo Boet (rboet at cenditel.gob.ve)
        @copyright GNU/GPLv3
        @date 20-11-2017
        @param self <b>{object}</b> Objeto que instancia la clase
        @param kwargs <b>{object}</b> Objeto que contiene los datos de contexto
        @return Retorna los datos de contexto
        """
        evento = int(self.kwargs['pk'])
        context = super(DetailEvent, self).get_context_data(**kwargs)
        try:
            participante_evento = ParticipanteEvento.objects.select_related().filter(fk_evento=evento)
            falta_porfirma = participante_evento.filter(firma=False).count()
        except Exception as e:
            print(e)
            participante_evento = None
            falta_porfirma = None
        context['participantes'] = participante_evento
        context['num_firma'] = falta_porfirma
        return context


@method_decorator(csrf_exempt, name='dispatch')
class EventoProcesado(View):
    """!
    Clase que permite consultar si el evento se encuentra disponible para firmar

    @author Ing. Leonel P. Hernandez M. (lhernandez at cenditel.gob.ve)
    @copyright <a href='https://www.gnu.org/licenses/gpl-3.0.en.html'>GNU Public License versión 3 (GPLv3)</a>
    @date 27-11-2017
    @version 1.0.0
    """
    model = Evento

    def get(self, request, event_id):
        """!
        Metodo que permite verificar si el documento esta procesado

eventos/templates/evento.detail.html
{% extends 'base.template.html' %}
{% load staticfiles %}
{% block title %}Detalle del Evento {{ object.nombre_evento }}{% endblock %}
{% block content %}
    <h1 class="center">Evento: {{ object.nombre_evento }}</h1><hr>
    
    <div class="row">
        <div class="col s12 m12">
            <div class="card">
                <div class="card-content">
                    <span class="card-title"><b>Nombre del evento: </b>{{ object.nombre_evento }}</span>
                    <ul>
                        <li><b>Fecha: </b>{{ object.fecha }}</li>
                    </ul>
                    <ul>
                        <li><b>Activo: </b>{% if object.activo %}
                            Sí, el documento si se encuentra activo aún falta {{num_firma}} {% if num_firma > 1 %}participantes {% else %} participante {% endif%} por firmar</li>
                        {% else %}
                            No, el documento no esta activo todos los participantes han firmado</li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    <div class="col s12 m12">
        <table class="responsive-table striped">
        <h4> Participantes</h4>
            <thead>
              <tr>
                  <th scope="col">Nombresy Apellidos</th>
                  <th scope="col">¿Firmó?</th>
              </tr>
            </thead>
            <tbody>
                {% for firmantes in participantes %}
                    <tr>
                        <td>
                            {{ firmantes.fk_participante.nombres }} {{ firmantes.fk_participante.apellidos }}
                        </td>
                        <td>
                            {% if firmantes.firma %}
                                <i class="material-icons green-text" title="Sí">done</i>
                            {% else %}
                                <i class="material-icons red-text" title="No">clear</i>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        </div>
    </div>
    <div class="center">
        {% if object.serial %}
        <iframe width="700px" height="600px" src="https://localhost:8443/Murachi/0.1/archivos/listadopdf/{{object.serial}}">';
        </iframe>
        {% else %}
            <h4 class="red-text">No cargó ningun documento</h4>
        {% endif %}
    </div>
    <div class="row">
        <a class="btn waves-effect colorazul" href="{% url 'events:list_events' %}" >Regresar</a>
    </div>
{% endblock %}

eventos/templates/evento.firma.html
{% extends 'base.template.html' %}
{% load staticfiles %}
{% block title %}Firmar Evento{% endblock title %}
{% block content %}
    <div class="content center">
        <h3>{{nombre_evento}}</h3>
        <form id="form" method="post">
            {% csrf_token %}
            <div class="input-field {% if form.pasaporte.errors %}invalid{% endif %}">
                {{ form.pasaporte }}
                <label for="icon_prefix {{ form.pasaporte.auto_id }}">Número de Pasaporte</label>
                {% include 'base.forms.errors.html' with form_errors=form.pasaporte.errors col_title_error='col s2' col_msg_error='col s10' %}
            </div>
            
            <a type="button" class="btn waves-effect colorazul" onclick="get_event_user()">
                <i class="material-icons left">search</i> Buscar
            </a>
            {% if nombre_evento.serial %}
                <div id="datos_paricipante"></div>
            {% else %}
                <h3>No existe Documento para firmar</h3>
            {% endif %}
        </form>
        <div class="row" style="padding-top: 25px;">
            <a class="btn left waves-effect colorazul" href="{% url 'events:list_events' %}" >Regresar</a>
        </div>
    </div>
{% endblock %}
{% block extraJs %}
    <script type="text/javascript" src="{% static "plugins/hwcrypto/gitversion.js"  %}"></script>
    <script type="text/javascript" src="{% static "plugins/hwcrypto/hwcrypto-legacy.js"  %}"></script>
    <script type="text/javascript" src="{% static "plugins/hwcrypto/hwcrypto.js"  %}"></script>
    <script type="text/javascript" src="{% static "plugins/hwcrypto/hex2base.js"  %}"></script> 
    <script type="text/javascript" src="{% static "plugins/base64/jquery.base64.js"  %}"></script> 
{% endblock %}

eventos/templates/evento.list.html
{% extends 'base.template.html' %}
{% load staticfiles %}
{% block title %}Eventos{% endblock %}
{% block content %}
    <h1 class="center">Eventos</h1><hr>
    
    {% if request.user.is_authenticated %}
        <div class="row content">
            <a type="button" class="btn waves-effect btn colorazul right" href="{% url 'events:create_events' %}">
                <i class="material-icons left">add_circle</i> Registrar Nuevo Evento</a>
        </div>
    {% endif %}
    
    {% for evento in object_list %}
        <div class="card">
            <div class="card-content">
                <span class="card-title"><b>Nombre del evento: </b>{{ evento.nombre_evento }}</span>
                <ul>
                    <li><b>Fecha: </b>{{ evento.fecha }}</li>
                </ul>
            </div>
            <div class="card-action">
                <a type="button" class="btn waves-effect colorazul" href="{% url 'events:detail_event' evento.id %}">
                    <i class="material-icons left">search</i> Detalle
                </a>
                {% if evento.serial %}
                <a type="button" class="btn waves-effect colorazul" href="{% url 'events:firma_events' evento.id %}">
                    <i class="material-icons left">mode_edit</i> Firmar
                </a>
                {% endif %}
                {% if request.user.is_authenticated %}
                    <a type="button" class="btn waves-effect colorazul" href="{% url 'events:update_evento' evento.id %}">
                        <i class="material-icons left">backup</i> Cargar Documento
                    </a>
                {% endif %}
                
                {% if request.user.is_authenticated %}
                    <a type"button" class="btn waves-effect colorazul" href="{% url  'events:update_evento_participante' evento.id %}"><i class="material-icons left">border_color</i>Editar Evento
                    </a>
                {% endif %}
            </div>
        </div>
    {% empty %}
        <h3>No existen eventos.</h3>
    {% endfor %}
    {% include 'base.paginator.html' with paginator=page_obj %}
    <div style="padding-bottom: 50px;">
        <a type="button" class="btn waves-effect btn colorazul" href="{% url 'base:inicio' %}">Regresar</a>
    </div>
{% endblock %}

eventos/templates/evento.update.html
{% extends 'base.template.html' %}
{% load staticfiles %}
{% block title %}Cargar Archivo{% endblock title %}
{% block extraJs %}
    <script src="{% static 'js/jquery/jquery-ui.js' %}"></script>
    <script src="{% static 'js/pdf.js' %}"></script>
    <script src="{% static 'js/pdf.worker.js' %}"></script>
    <script src="{% static 'js/draggable.js' %}"></script>
    <!-- Coordenadas PDF-->
    <script src="{% static 'js/DraggableSortable.js' %}"></script>
    <script src="{% static 'js/docsDraggable.js' %}"></script>
    
{%endblock%}

{% block content %}
    <div class="content">
        {% if valida %}
        <div class="center">
          <h5 class="center">El evento {{object.nombre_evento}}, ya contiene un documento</h5><hr/><br>
          <iframe width="700px" height="600px" src="https://localhost:8443/Murachi/0.1/archivos/listadopdf/{{object.serial}}">';
          </iframe>
        </div>
        {% else %}
        <h5 class="center">Cargar Archivo al Evento</h5><hr/><br>
        <h5 class="blue-text">Luego de cargar un documento debe colocar el código Qr en la ubicación y página de su preferencia.</h5>
        <form id="form" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            
            <div class="file-field input-field {% if form.archivo.errors %}invalid{% endif %}">
                
                <div class="btn">
                    <span for="icon_prefix {{ form.archivo.auto_id }}">Archivo</span>
                    <input type="file" name="file" id="file" accept="application/pdf">
                </div>
                <div class="file-path-wrapper">
                    {{ form.archivo }}
                </div>
                {% include 'base.forms.errors.html' with form_errors=form.archivo.errors col_title_error='col s2' col_msg_error='col s10' %}
                
            </div>

            <div class="col s8 m2 offset-s2">
                <div id="pdf-main-container" style="display:none;"><center><h5>Configurar Posicion de la Firma</h5></center> 
                      <div id="pdf-loader2">Cargando documento ...</div>
                      <div id="pdf-contents2">
                        <div id="pdf-meta2">
                          <div id="pdf-buttons2">
                            <a class="waves-effect waves-light btn" id="pdf-prev2"><i class="material-icons">keyboard_arrow_left</i></a>
                            <a class="waves-effect waves-light btn" id="pdf-next2"><i class="material-icons">keyboard_arrow_right</i></a>
                          </div>
                          <div id="page-count-container">Página <span id="pdf-current-page2"></span> de <span id="pdf-total-pages2"></span></div>
                        </div>
                        <img class="text" src="{% static 'img/QRCode.png' %}" id="texto"/>
                        <div class="overflow" >
                          <div id="container1" class=".cropper-hidden">
                            <!--<div class="ball blue">sdsa</div>-->
                          </div>
                          <br>
                          <br>
                        </div>          
                        </div>
                        <canvas id="pdf-canvas2" width="500"></canvas>
                        <div id="page-loader2">Cargando página ...</div>
                  </div>
                  {{ form.pos_x }}
                  {{ form.pos_y }}
                  {{ form.pag }}
            </div>
            
            <div class="center">
                <button type="submit" class="btn waves-effect colorazul">Cargar Archivo</button>
            </div>
            </div>
        </form>
        {% endif %}
    </div>
{% endblock %}